import { REPORTING_DATASETS } from "../src/reporting-contract.js";

const clock = "strftime('%Y-%m-%dT%H:%M:%fZ', 'now')";
const generation = "(SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1)";
const fields = "feed_generation, dataset, record_id, revision, operation, changed_at, record_json";
const projection = (dataset, alias) => "json_object(" + dataset.columns
  .map(column => `'${column}', ${alias}.${column}`).join(", ") + ")";

export function bootstrapStatements() {
  return REPORTING_DATASETS.map(dataset =>
    `INSERT INTO mirror_changes (${fields})\nSELECT ${generation}, '${dataset.name}', r.${dataset.key}, 1, 'upsert', ${clock},\n       ${projection(dataset, "r")}\nFROM ${dataset.name} r ORDER BY r.${dataset.key};`);
}

export function reseedStatements() {
  return [
    `UPDATE mirror_feed_state SET feed_generation = lower(hex(randomblob(16))), created_at = ${clock} WHERE singleton = 1;`,
    ...bootstrapStatements()
  ];
}

export function migrationStatements() {
  const statements = [
    `CREATE TABLE mirror_feed_state (\n  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),\n  feed_generation TEXT NOT NULL UNIQUE,\n  created_at TEXT NOT NULL\n);`,
    `INSERT INTO mirror_feed_state VALUES (1, lower(hex(randomblob(16))), ${clock});`,
    "ALTER TABLE mirror_changes ADD COLUMN record_json TEXT;",
    "CREATE INDEX idx_mirror_generation_sequence ON mirror_changes(feed_generation, sequence);",
    "CREATE UNIQUE INDEX idx_mirror_record_revision ON mirror_changes(feed_generation, dataset, record_id, revision);",
    "CREATE TABLE nonparticipant_press_receipts (request_id TEXT PRIMARY KEY, button_id TEXT NOT NULL, created_at TEXT NOT NULL);",
    ...bootstrapStatements()
  ];
  for (const dataset of REPORTING_DATASETS) {
    statements.push(`CREATE TRIGGER mirror_${dataset.name}_key BEFORE UPDATE OF ${dataset.key} ON ${dataset.name}\nWHEN OLD.${dataset.key} IS NOT NEW.${dataset.key}\nBEGIN\n  SELECT RAISE(ABORT, 'Reporting record keys are immutable');\nEND;`);
    for (const event of ["INSERT", "UPDATE", "DELETE"]) {
      const alias = event === "DELETE" ? "OLD" : "NEW";
      const operation = event === "DELETE" ? "delete" : "upsert";
      const when = event === "UPDATE" ? "\nWHEN " + dataset.columns
        .map(column => `OLD.${column} IS NOT NEW.${column}`).join("\n  OR ") : "";
      const revision = `(SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes\n     WHERE feed_generation = ${generation} AND dataset = '${dataset.name}' AND record_id = ${alias}.${dataset.key})`;
      statements.push(`CREATE TRIGGER mirror_${dataset.name}_${event.toLowerCase()} AFTER ${event} ON ${dataset.name}${when}\nBEGIN\n  INSERT INTO mirror_changes (${fields})\n  VALUES (${generation}, '${dataset.name}', ${alias}.${dataset.key},\n    ${revision}, '${operation}', ${clock},\n    ${event === "DELETE" ? "NULL" : projection(dataset, alias)});\nEND;`);
    }
  }
  return statements;
}

export const migrationSql = () => "-- Generated by scripts/generate-reporting-schema.mjs; contains no study data.\n" +
  "-- Apply with D1 migrations (one transaction). Do not split trigger bodies.\n" +
  migrationStatements().join("\n\n") + "\n";
