-- Generated by scripts/generate-reporting-schema.mjs; contains no study data.
-- Apply with D1 migrations (one transaction). Do not split trigger bodies.
CREATE TABLE mirror_feed_state (
  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
  feed_generation TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
);

INSERT INTO mirror_feed_state VALUES (1, lower(hex(randomblob(16))), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));

ALTER TABLE mirror_changes ADD COLUMN record_json TEXT;

CREATE INDEX idx_mirror_generation_sequence ON mirror_changes(feed_generation, sequence);

CREATE UNIQUE INDEX idx_mirror_record_revision ON mirror_changes(feed_generation, dataset, record_id, revision);

CREATE TABLE nonparticipant_press_receipts (request_id TEXT PRIMARY KEY, button_id TEXT NOT NULL, created_at TEXT NOT NULL);

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_submissions', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'participant_id', r.participant_id, 'session_id', r.session_id, 'context_id', r.context_id, 'status', r.status, 'session_start', r.session_start, 'submitted_at', r.submitted_at, 'llm_product', r.llm_product, 'llm_model', r.llm_model, 'llm_description', r.llm_description, 'course_context', r.course_context, 'question_context', r.question_context, 'extra_instructions', r.extra_instructions, 'desired_questions', r.desired_questions, 'final_response', r.final_response, 'feedback_text', r.feedback_text, 'audio_object_key', r.audio_object_key, 'audio_duration_seconds', r.audio_duration_seconds, 'active_seconds', r.active_seconds, 'session_close_type', r.session_close_type, 'session_close_at', r.session_close_at, 'app_version', r.app_version, 'mode', r.mode, 'created_at', r.created_at)
FROM aqg_submissions r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_events', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'event_id', r.event_id, 'batch_id', r.batch_id, 'event_timestamp', r.event_timestamp, 'ms_since_previous', r.ms_since_previous, 'participant_id', r.participant_id, 'session_id', r.session_id, 'context_id', r.context_id, 'event_type', r.event_type, 'button_id', r.button_id, 'detail_text', r.detail_text, 'detail_json', r.detail_json, 'device_label', r.device_label, 'created_at', r.created_at)
FROM aqg_events r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_feedback', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'feedback_id', r.feedback_id, 'participant_id', r.participant_id, 'session_id', r.session_id, 'submitted_at', r.submitted_at, 'text_feedback', r.text_feedback, 'audio_object_key', r.audio_object_key, 'audio_original_filename', r.audio_original_filename, 'audio_mime_type', r.audio_mime_type, 'audio_duration_seconds', r.audio_duration_seconds, 'created_at', r.created_at)
FROM aqg_feedback r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submissions', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'participant_id', r.participant_id, 'session_id', r.session_id, 'session_seq', r.session_seq, 'session_start', r.session_start, 'session_end', r.session_end, 'duration_ms', r.duration_ms, 'duration_formatted', r.duration_formatted, 'active_seconds', r.active_seconds, 'total_questions', r.total_questions, 'correct_first', r.correct_first, 'event_count', r.event_count, 'item_count', r.item_count, 'app_version', r.app_version, 'content_version', r.content_version, 'current_card_number', r.current_card_number, 'device_trail', r.device_trail, 'submitted_at', r.submitted_at, 'created_at', r.created_at)
FROM training_submissions r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submission_items', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'participant_id', r.participant_id, 'session_id', r.session_id, 'content_version', r.content_version, 'item_number', r.item_number, 'response_text', r.response_text, 'response_ms', r.response_ms, 'created_at', r.created_at)
FROM training_submission_items r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_events', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'event_id', r.event_id, 'batch_id', r.batch_id, 'event_timestamp', r.event_timestamp, 'ms_since_previous', r.ms_since_previous, 'participant_id', r.participant_id, 'session_id', r.session_id, 'session_seq', r.session_seq, 'event_type', r.event_type, 'section_index', r.section_index, 'card_index', r.card_index, 'detail_text', r.detail_text, 'detail_json', r.detail_json, 'device_label', r.device_label, 'created_at', r.created_at)
FROM training_events r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_feedback', r.record_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('record_id', r.record_id, 'feedback_id', r.feedback_id, 'participant_id', r.participant_id, 'session_id', r.session_id, 'session_seq', r.session_seq, 'submitted_at', r.submitted_at, 'section_index', r.section_index, 'section_title', r.section_title, 'card_index', r.card_index, 'feedback_source', r.feedback_source, 'text_feedback', r.text_feedback, 'device_label', r.device_label, 'created_at', r.created_at)
FROM training_feedback r ORDER BY r.record_id;

INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
SELECT (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'nonparticipant_button_counts', r.button_id, 1, 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       json_object('button_id', r.button_id, 'press_count', r.press_count, 'updated_at', r.updated_at)
FROM nonparticipant_button_counts r ORDER BY r.button_id;

CREATE TRIGGER mirror_aqg_submissions_key BEFORE UPDATE OF record_id ON aqg_submissions
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_aqg_submissions_insert AFTER INSERT ON aqg_submissions
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_submissions', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_submissions' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'context_id', NEW.context_id, 'status', NEW.status, 'session_start', NEW.session_start, 'submitted_at', NEW.submitted_at, 'llm_product', NEW.llm_product, 'llm_model', NEW.llm_model, 'llm_description', NEW.llm_description, 'course_context', NEW.course_context, 'question_context', NEW.question_context, 'extra_instructions', NEW.extra_instructions, 'desired_questions', NEW.desired_questions, 'final_response', NEW.final_response, 'feedback_text', NEW.feedback_text, 'audio_object_key', NEW.audio_object_key, 'audio_duration_seconds', NEW.audio_duration_seconds, 'active_seconds', NEW.active_seconds, 'session_close_type', NEW.session_close_type, 'session_close_at', NEW.session_close_at, 'app_version', NEW.app_version, 'mode', NEW.mode, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_aqg_submissions_update AFTER UPDATE ON aqg_submissions
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.context_id IS NOT NEW.context_id
  OR OLD.status IS NOT NEW.status
  OR OLD.session_start IS NOT NEW.session_start
  OR OLD.submitted_at IS NOT NEW.submitted_at
  OR OLD.llm_product IS NOT NEW.llm_product
  OR OLD.llm_model IS NOT NEW.llm_model
  OR OLD.llm_description IS NOT NEW.llm_description
  OR OLD.course_context IS NOT NEW.course_context
  OR OLD.question_context IS NOT NEW.question_context
  OR OLD.extra_instructions IS NOT NEW.extra_instructions
  OR OLD.desired_questions IS NOT NEW.desired_questions
  OR OLD.final_response IS NOT NEW.final_response
  OR OLD.feedback_text IS NOT NEW.feedback_text
  OR OLD.audio_object_key IS NOT NEW.audio_object_key
  OR OLD.audio_duration_seconds IS NOT NEW.audio_duration_seconds
  OR OLD.active_seconds IS NOT NEW.active_seconds
  OR OLD.session_close_type IS NOT NEW.session_close_type
  OR OLD.session_close_at IS NOT NEW.session_close_at
  OR OLD.app_version IS NOT NEW.app_version
  OR OLD.mode IS NOT NEW.mode
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_submissions', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_submissions' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'context_id', NEW.context_id, 'status', NEW.status, 'session_start', NEW.session_start, 'submitted_at', NEW.submitted_at, 'llm_product', NEW.llm_product, 'llm_model', NEW.llm_model, 'llm_description', NEW.llm_description, 'course_context', NEW.course_context, 'question_context', NEW.question_context, 'extra_instructions', NEW.extra_instructions, 'desired_questions', NEW.desired_questions, 'final_response', NEW.final_response, 'feedback_text', NEW.feedback_text, 'audio_object_key', NEW.audio_object_key, 'audio_duration_seconds', NEW.audio_duration_seconds, 'active_seconds', NEW.active_seconds, 'session_close_type', NEW.session_close_type, 'session_close_at', NEW.session_close_at, 'app_version', NEW.app_version, 'mode', NEW.mode, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_aqg_submissions_delete AFTER DELETE ON aqg_submissions
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_submissions', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_submissions' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_aqg_events_key BEFORE UPDATE OF record_id ON aqg_events
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_aqg_events_insert AFTER INSERT ON aqg_events
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_events', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_events' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'event_id', NEW.event_id, 'batch_id', NEW.batch_id, 'event_timestamp', NEW.event_timestamp, 'ms_since_previous', NEW.ms_since_previous, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'context_id', NEW.context_id, 'event_type', NEW.event_type, 'button_id', NEW.button_id, 'detail_text', NEW.detail_text, 'detail_json', NEW.detail_json, 'device_label', NEW.device_label, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_aqg_events_update AFTER UPDATE ON aqg_events
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.event_id IS NOT NEW.event_id
  OR OLD.batch_id IS NOT NEW.batch_id
  OR OLD.event_timestamp IS NOT NEW.event_timestamp
  OR OLD.ms_since_previous IS NOT NEW.ms_since_previous
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.context_id IS NOT NEW.context_id
  OR OLD.event_type IS NOT NEW.event_type
  OR OLD.button_id IS NOT NEW.button_id
  OR OLD.detail_text IS NOT NEW.detail_text
  OR OLD.detail_json IS NOT NEW.detail_json
  OR OLD.device_label IS NOT NEW.device_label
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_events', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_events' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'event_id', NEW.event_id, 'batch_id', NEW.batch_id, 'event_timestamp', NEW.event_timestamp, 'ms_since_previous', NEW.ms_since_previous, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'context_id', NEW.context_id, 'event_type', NEW.event_type, 'button_id', NEW.button_id, 'detail_text', NEW.detail_text, 'detail_json', NEW.detail_json, 'device_label', NEW.device_label, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_aqg_events_delete AFTER DELETE ON aqg_events
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_events', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_events' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_aqg_feedback_key BEFORE UPDATE OF record_id ON aqg_feedback
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_aqg_feedback_insert AFTER INSERT ON aqg_feedback
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_feedback', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_feedback' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'feedback_id', NEW.feedback_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'submitted_at', NEW.submitted_at, 'text_feedback', NEW.text_feedback, 'audio_object_key', NEW.audio_object_key, 'audio_original_filename', NEW.audio_original_filename, 'audio_mime_type', NEW.audio_mime_type, 'audio_duration_seconds', NEW.audio_duration_seconds, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_aqg_feedback_update AFTER UPDATE ON aqg_feedback
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.feedback_id IS NOT NEW.feedback_id
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.submitted_at IS NOT NEW.submitted_at
  OR OLD.text_feedback IS NOT NEW.text_feedback
  OR OLD.audio_object_key IS NOT NEW.audio_object_key
  OR OLD.audio_original_filename IS NOT NEW.audio_original_filename
  OR OLD.audio_mime_type IS NOT NEW.audio_mime_type
  OR OLD.audio_duration_seconds IS NOT NEW.audio_duration_seconds
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_feedback', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_feedback' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'feedback_id', NEW.feedback_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'submitted_at', NEW.submitted_at, 'text_feedback', NEW.text_feedback, 'audio_object_key', NEW.audio_object_key, 'audio_original_filename', NEW.audio_original_filename, 'audio_mime_type', NEW.audio_mime_type, 'audio_duration_seconds', NEW.audio_duration_seconds, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_aqg_feedback_delete AFTER DELETE ON aqg_feedback
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'aqg_feedback', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'aqg_feedback' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_training_submissions_key BEFORE UPDATE OF record_id ON training_submissions
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_training_submissions_insert AFTER INSERT ON training_submissions
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submissions', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_submissions' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'session_seq', NEW.session_seq, 'session_start', NEW.session_start, 'session_end', NEW.session_end, 'duration_ms', NEW.duration_ms, 'duration_formatted', NEW.duration_formatted, 'active_seconds', NEW.active_seconds, 'total_questions', NEW.total_questions, 'correct_first', NEW.correct_first, 'event_count', NEW.event_count, 'item_count', NEW.item_count, 'app_version', NEW.app_version, 'content_version', NEW.content_version, 'current_card_number', NEW.current_card_number, 'device_trail', NEW.device_trail, 'submitted_at', NEW.submitted_at, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_submissions_update AFTER UPDATE ON training_submissions
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.session_seq IS NOT NEW.session_seq
  OR OLD.session_start IS NOT NEW.session_start
  OR OLD.session_end IS NOT NEW.session_end
  OR OLD.duration_ms IS NOT NEW.duration_ms
  OR OLD.duration_formatted IS NOT NEW.duration_formatted
  OR OLD.active_seconds IS NOT NEW.active_seconds
  OR OLD.total_questions IS NOT NEW.total_questions
  OR OLD.correct_first IS NOT NEW.correct_first
  OR OLD.event_count IS NOT NEW.event_count
  OR OLD.item_count IS NOT NEW.item_count
  OR OLD.app_version IS NOT NEW.app_version
  OR OLD.content_version IS NOT NEW.content_version
  OR OLD.current_card_number IS NOT NEW.current_card_number
  OR OLD.device_trail IS NOT NEW.device_trail
  OR OLD.submitted_at IS NOT NEW.submitted_at
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submissions', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_submissions' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'session_seq', NEW.session_seq, 'session_start', NEW.session_start, 'session_end', NEW.session_end, 'duration_ms', NEW.duration_ms, 'duration_formatted', NEW.duration_formatted, 'active_seconds', NEW.active_seconds, 'total_questions', NEW.total_questions, 'correct_first', NEW.correct_first, 'event_count', NEW.event_count, 'item_count', NEW.item_count, 'app_version', NEW.app_version, 'content_version', NEW.content_version, 'current_card_number', NEW.current_card_number, 'device_trail', NEW.device_trail, 'submitted_at', NEW.submitted_at, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_submissions_delete AFTER DELETE ON training_submissions
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submissions', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_submissions' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_training_submission_items_key BEFORE UPDATE OF record_id ON training_submission_items
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_training_submission_items_insert AFTER INSERT ON training_submission_items
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submission_items', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_submission_items' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'content_version', NEW.content_version, 'item_number', NEW.item_number, 'response_text', NEW.response_text, 'response_ms', NEW.response_ms, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_submission_items_update AFTER UPDATE ON training_submission_items
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.content_version IS NOT NEW.content_version
  OR OLD.item_number IS NOT NEW.item_number
  OR OLD.response_text IS NOT NEW.response_text
  OR OLD.response_ms IS NOT NEW.response_ms
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submission_items', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_submission_items' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'content_version', NEW.content_version, 'item_number', NEW.item_number, 'response_text', NEW.response_text, 'response_ms', NEW.response_ms, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_submission_items_delete AFTER DELETE ON training_submission_items
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_submission_items', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_submission_items' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_training_events_key BEFORE UPDATE OF record_id ON training_events
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_training_events_insert AFTER INSERT ON training_events
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_events', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_events' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'event_id', NEW.event_id, 'batch_id', NEW.batch_id, 'event_timestamp', NEW.event_timestamp, 'ms_since_previous', NEW.ms_since_previous, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'session_seq', NEW.session_seq, 'event_type', NEW.event_type, 'section_index', NEW.section_index, 'card_index', NEW.card_index, 'detail_text', NEW.detail_text, 'detail_json', NEW.detail_json, 'device_label', NEW.device_label, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_events_update AFTER UPDATE ON training_events
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.event_id IS NOT NEW.event_id
  OR OLD.batch_id IS NOT NEW.batch_id
  OR OLD.event_timestamp IS NOT NEW.event_timestamp
  OR OLD.ms_since_previous IS NOT NEW.ms_since_previous
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.session_seq IS NOT NEW.session_seq
  OR OLD.event_type IS NOT NEW.event_type
  OR OLD.section_index IS NOT NEW.section_index
  OR OLD.card_index IS NOT NEW.card_index
  OR OLD.detail_text IS NOT NEW.detail_text
  OR OLD.detail_json IS NOT NEW.detail_json
  OR OLD.device_label IS NOT NEW.device_label
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_events', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_events' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'event_id', NEW.event_id, 'batch_id', NEW.batch_id, 'event_timestamp', NEW.event_timestamp, 'ms_since_previous', NEW.ms_since_previous, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'session_seq', NEW.session_seq, 'event_type', NEW.event_type, 'section_index', NEW.section_index, 'card_index', NEW.card_index, 'detail_text', NEW.detail_text, 'detail_json', NEW.detail_json, 'device_label', NEW.device_label, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_events_delete AFTER DELETE ON training_events
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_events', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_events' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_training_feedback_key BEFORE UPDATE OF record_id ON training_feedback
WHEN OLD.record_id IS NOT NEW.record_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_training_feedback_insert AFTER INSERT ON training_feedback
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_feedback', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_feedback' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'feedback_id', NEW.feedback_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'session_seq', NEW.session_seq, 'submitted_at', NEW.submitted_at, 'section_index', NEW.section_index, 'section_title', NEW.section_title, 'card_index', NEW.card_index, 'feedback_source', NEW.feedback_source, 'text_feedback', NEW.text_feedback, 'device_label', NEW.device_label, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_feedback_update AFTER UPDATE ON training_feedback
WHEN OLD.record_id IS NOT NEW.record_id
  OR OLD.feedback_id IS NOT NEW.feedback_id
  OR OLD.participant_id IS NOT NEW.participant_id
  OR OLD.session_id IS NOT NEW.session_id
  OR OLD.session_seq IS NOT NEW.session_seq
  OR OLD.submitted_at IS NOT NEW.submitted_at
  OR OLD.section_index IS NOT NEW.section_index
  OR OLD.section_title IS NOT NEW.section_title
  OR OLD.card_index IS NOT NEW.card_index
  OR OLD.feedback_source IS NOT NEW.feedback_source
  OR OLD.text_feedback IS NOT NEW.text_feedback
  OR OLD.device_label IS NOT NEW.device_label
  OR OLD.created_at IS NOT NEW.created_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_feedback', NEW.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_feedback' AND record_id = NEW.record_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('record_id', NEW.record_id, 'feedback_id', NEW.feedback_id, 'participant_id', NEW.participant_id, 'session_id', NEW.session_id, 'session_seq', NEW.session_seq, 'submitted_at', NEW.submitted_at, 'section_index', NEW.section_index, 'section_title', NEW.section_title, 'card_index', NEW.card_index, 'feedback_source', NEW.feedback_source, 'text_feedback', NEW.text_feedback, 'device_label', NEW.device_label, 'created_at', NEW.created_at));
END;

CREATE TRIGGER mirror_training_feedback_delete AFTER DELETE ON training_feedback
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'training_feedback', OLD.record_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'training_feedback' AND record_id = OLD.record_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;

CREATE TRIGGER mirror_nonparticipant_button_counts_key BEFORE UPDATE OF button_id ON nonparticipant_button_counts
WHEN OLD.button_id IS NOT NEW.button_id
BEGIN
  SELECT RAISE(ABORT, 'Reporting record keys are immutable');
END;

CREATE TRIGGER mirror_nonparticipant_button_counts_insert AFTER INSERT ON nonparticipant_button_counts
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'nonparticipant_button_counts', NEW.button_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'nonparticipant_button_counts' AND record_id = NEW.button_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('button_id', NEW.button_id, 'press_count', NEW.press_count, 'updated_at', NEW.updated_at));
END;

CREATE TRIGGER mirror_nonparticipant_button_counts_update AFTER UPDATE ON nonparticipant_button_counts
WHEN OLD.button_id IS NOT NEW.button_id
  OR OLD.press_count IS NOT NEW.press_count
  OR OLD.updated_at IS NOT NEW.updated_at
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'nonparticipant_button_counts', NEW.button_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'nonparticipant_button_counts' AND record_id = NEW.button_id), 'upsert', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    json_object('button_id', NEW.button_id, 'press_count', NEW.press_count, 'updated_at', NEW.updated_at));
END;

CREATE TRIGGER mirror_nonparticipant_button_counts_delete AFTER DELETE ON nonparticipant_button_counts
BEGIN
  INSERT INTO mirror_changes (feed_generation, dataset, record_id, revision, operation, changed_at, record_json)
  VALUES ((SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1), 'nonparticipant_button_counts', OLD.button_id,
    (SELECT COALESCE(MAX(revision), 0) + 1 FROM mirror_changes
     WHERE feed_generation = (SELECT feed_generation FROM mirror_feed_state WHERE singleton = 1) AND dataset = 'nonparticipant_button_counts' AND record_id = OLD.button_id), 'delete', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    NULL);
END;
